#!/bin/bash

export WORKDIR=`pwd`
pwd

jupyter-nbextension enable --py widgetsnbextension

pip install nglview
jupyter-nbextension enable nglview --py --sys-prefix

git clone https://github.com/TeamOverkill/md.git
cd md

#./scripts/compile.sh
