#!/bin/bash

export WORKDIR=`pwd`
pwd

jupyter-nbextension enable --py widgetsnbextension
jupyter-nbextension enable nglview --py --sys-prefix

git clone https://github.com/TeamOverkill/md.git
cd md
git checkout experimental
cd src
#mv Atoms.h atoms.h


#cat << EOF >> Compile.sh
#gcc -c main.cpp base.cpp atom.cpp atoms.cpp frame.cpp ran2_lib.cpp -O3 -march=native -Xpreprocessor -std=c++17 -I /srv/conda/envs/notebook/include/eigen3 -lm -ldl
#gcc -o main main.o base.o atom.o atoms.o frame.o ran2_lib.o ran2.o -O3 -march=native -lstdc++ -lgomp -lm -ldl
#EOF

#chmod u+x Compile.sh
#./Compile.sh
